<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="lachiravi" failures="0" tests="2" name="com.myapp.test.SignInTest" time="0.920" errors="1" timestamp="2022-07-28T17:07:03 IST" skipped="1">
  <testcase classname="com.myapp.test.SignInTest" name="invalidLoginTest" time="0.000">
    <skipped/>
  </testcase> <!-- invalidLoginTest -->
  <system-out/>
  <testcase classname="com.myapp.test.SignInTest" name="suiteSetUp" time="0.920">
    <error message="Configuration.properties not found at E:\FeameWork\KSRTC2/src/test/resources/configuration.properties" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Configuration.properties not found at E:\FeameWork\KSRTC2/src/test/resources/configuration.properties
at com.sjm.utilities.ConfigProperties.<init>(ConfigProperties.java:31)
at com.sjm.utilities.BaseSuiteSetUp.suiteSetUp(BaseSuiteSetUp.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- suiteSetUp -->
  <system-out/>
</testsuite> <!-- com.myapp.test.SignInTest -->
